[package]
name = "kms_enclave"
version = "0.1.0"
authors = ["MesaTEE Authors <developers@mesatee.org>"]
description = "Key management service."
license = "Apache-2.0"
edition = "2018"

[lib]
name = "kms_enclave"
crate-type = ["staticlib"]

[features]
default = []
mesalock_sgx = ["sgx_tstd", "mesatee_core/mesalock_sgx", "kms_proto/mesalock_sgx"]
cov = ["sgx_cov"]

[dependencies]
cfg-if          = { version = "0.1.9" }
lazy_static     = { version = "1.0.2", features = ["spin_no_std"] }
log             = { version = "0.4.6" }
env_logger      = { version = "0.7.1" }
uuid            = { version = "0.7.4", features = ["v4"] }
rand            = { version = "0.7.0" }

kms_proto       = { path = "../proto", optional = true}
mesatee_core    = { version = "0.1.0" }

sgx_cov         = { version = "0.1.0", optional = true }
sgx_tstd        = { version = "1.0.9", features = ["net", "backtrace"], optional = true }
sgx_types       = { version = "1.0.9" }
