[package]
name = "tdfs_internal_client"
version = "0.1.0"
authors = ["MesaTEE Authors <developers@mesatee.org>"]
description = "RPC client of TDFS."
license = "Apache-2.0"
edition = "2018"

[features]
default = []
mesalock_sgx = ["sgx_tstd", "mesatee_core/mesalock_sgx", "kms_proto/mesalock_sgx", "tdfs_internal_proto/mesalock_sgx"]
cov = ["sgx_cov"]

[dependencies]
cfg-if       = { version = "0.1.9" }
ring         = { version = "0.16.5" }
net2         = { version = "0.2.33" }

kms_proto          = { path = "../../../kms/proto", optional = true}
tdfs_internal_proto = { path = "../proto", optional = true}

mesatee_core    = { version = "0.1.0" }

sgx_cov         = { version = "0.1.0", optional = true }
sgx_tstd        = { version = "1.0.9", optional = true }
sgx_types       = { version = "1.0.9" }
